# Generated by Django 2.0.5 on 2018-05-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscript', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='num_classes',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='administrator',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('ESCOLAR', 'Escolar'), ('OTRO', 'Otro Dpto.')], max_length=10),
        ),
    ]
