# Generated by Django 2.0.5 on 2018-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscript', '0002_auto_20180506_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lab_slot',
            field=models.CharField(blank=True, choices=[('MAVI7', 'MaVi 7/3'), ('MAVI8', 'MaVi 8+/3'), ('MAVI10', 'MaVi 10/3'), ('MAVI11', 'MaVi 11+/3'), ('MAVI13', 'MaVi 13/3'), ('MAVI14', 'MaVi 14+/3'), ('MAVI16', 'MaVi 16/3'), ('MAVI18', 'MaVi 18/3'), ('LUJU7', 'LuJu 7/3'), ('LUJU8', 'LuJu 8+/3'), ('LUJU10', 'LuJu 10/3'), ('LUJU11', 'LuJu 11+/3'), ('LUJU13', 'LuJu 13/3'), ('LUJU14', 'LuJu 14+/3'), ('LUJU16', 'LuJu 16/3'), ('LUJU18', 'LuJu 18/3'), ('MI7', 'Mi 7/6'), ('MI10', 'Mi 10/6'), ('MI13', 'Mi 13/6'), ('MI14', 'Mi 14+/6')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_slot',
            field=models.CharField(choices=[('MAVI7', 'MaVi 7/3'), ('MAVI8', 'MaVi 8+/3'), ('MAVI10', 'MaVi 10/3'), ('MAVI11', 'MaVi 11+/3'), ('MAVI13', 'MaVi 13/3'), ('MAVI14', 'MaVi 14+/3'), ('MAVI16', 'MaVi 16/3'), ('MAVI18', 'MaVi 18/3'), ('LUJU7', 'LuJu 7/3'), ('LUJU8', 'LuJu 8+/3'), ('LUJU10', 'LuJu 10/3'), ('LUJU11', 'LuJu 11+/3'), ('LUJU13', 'LuJu 13/3'), ('LUJU14', 'LuJu 14+/3'), ('LUJU16', 'LuJu 16/3'), ('LUJU18', 'LuJu 18/3'), ('MI7', 'Mi 7/6'), ('MI10', 'Mi 10/6'), ('MI13', 'Mi 13/6'), ('MI14', 'Mi 14+/6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
